### ISSUE TITLE
Publish Workflow creates duplicate tags

### ISSUE THREAD

**Issue by mwbrooks** [slackapi/slack-github-action#127]
### Description

The publish workflow is created duplicate tags. The manual release steps creates a semver tag (e.g. `v1.20.0`) while the `JasonEtco/build-and-tag-action` action creates a second tag that's missing the patch (e.g. `v1.20`).

<img width="391" alt="image" src="https://user-images.githubusercontent.com/21328/189987913-33812b20-1670-434c-a34b-abd3b0909f47.png">

We may be able to fix this by [specifying the tag name](https://github.com/JasonEtco/build-and-tag-action#options) in the `JasonEtco/build-and-tag-action` action.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by filmaj** [comment]
Even with using the `with: tag_name: tagname` specifier for this action, it still seems like it is an issue (still happened for the v1.22.0 release).

**Comment by filmaj** [comment]
I filed https://github.com/JasonEtco/build-and-tag-action/issues/42 for this.

**Comment by zimeg** [comment]
:thinking: Could this be expected behavior to allow folks to pin a specific patch version or just use the latest patch of a minor version?

**Comment by filmaj** [comment]
Yeah I think so

**Comment by zimeg** [comment]
@filmaj I fell into the [source code rabbit hole](https://github.com/JasonEtco/build-and-tag-action/blob/main/src/lib/index.ts) and am also thinking this is intentional and worth keeping in the action 🤔

FWIW an interesting "branchless" commit is used to [keep these commits separate](https://github.com/slackapi/slack-github-action/commit/37ebaef184d7626c5f204ab8d3baff4262dd30f0) from `main` which seems to keep tag madness from happening 🤪  TIL!

Going to close this issue for housekeeping, but I'm open to revisting whenever!
