### ISSUE TITLE
If both webhook URL and bot token are specified, action will run twice

### ISSUE THREAD

**Issue by filmaj** [slackapi/slack-github-action#219]
### Description

I think this mostly just affects running the tests in this repo. Currently, each individual test in this repo's GH Action CI workflow file executes possibly multiple times because of this bug.

If a bot token is specified via an environment variable, then [this conditional block will execute](https://github.com/slackapi/slack-github-action/blob/main/src/slack-send.js#L64-L90), which might result in posting or updating a message.

If a webhook URL is specified via an environment varaible, then [this conditional block will execute](https://github.com/slackapi/slack-github-action/blob/main/src/slack-send.js#L92-L143), possibly POSTing to the webhook URL.

If you consume this action and use it using a bot token, but also specify the webhook URL environment variable, the action will POST to the webhook URL.

I think the solution is to do either-or: either use the bot token, or use the webhook URL. A fix for this issue should also clean up the usage of [the `webResponse` variable](https://github.com/slackapi/slack-github-action/blob/main/src/slack-send.js#L37C14-L37C14) in the code, as this is only set and used in the bot-token scenario.

**Comment by zimeg** [comment]
👋 This is now fixed with [`@v2`](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0) where including both `webhook` and `token` will [cause the step to exit](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0#only-one-technique-to-send-can-be-provided) with an error!

I do agree that having both techniques possible at the same time can cause a bit of confusion. I'd also be so interested in knowing of workflows that share payloads between different techniques in general 👀 

I'll close this issue with the latest changes 👍
