### ISSUE TITLE
Any way to create a channel and invite people from a set of user groups?

### ISSUE THREAD

**Issue by vyatpeloton** [slackapi/slack-github-action#270]
### Description

In the Workflow Builder, there doesn't appear to be any way to invite to a channel people from specified user groups. We can add people to a channel, but not groups. Nor is there an obvious way to populate a variable with the people in a set of user groups.

Can we add this feature? I think the most natural UI for this would be to support selecting user groups, not just people, in the dropdown for adding people to a channel.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by hello-ashleyintech** [comment]
Hi, @vyatpeloton! Thanks so much for submitting this issue. 🙌 

I have also tried to add a user group to a channel through Workflow Builder and was unable to locate user groups in the dropdown. Since this is more of a Workflow Builder issue, I have forwarded this feedback to the appropriate team internally to flag it as a future feature idea. I also have asked if they have any ideas for current workarounds for this.

Unfortunately, in the meantime, you'll likely need to manually add each user in the user group via the dropdown in Workflow Builder. I'll update this issue if we're able to identify any additional workarounds!

**Comment by zimeg** [comment]
👋 This is now possible in both Workflow Builder as part of the [`invite_user_to_channel`](https://api.slack.com/reference/functions/invite_user_to_channel) Slack function and is also included [in this example](https://github.com/slackapi/slack-github-action/blob/main/example-workflows/Technique_2_Slack_API_Method/invite.yml) using multiple Slack API methods!
